=== marcelo-6/ftbatch-recipe-bulk-edit/tests/MasterRecipe.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Studio (https://www.liquid-technologies.com) -->
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="urn:Rockwell/MasterRecipe" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="RecipeElement">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" name="RecipeElementID" type="xs:string" />
        <xs:element minOccurs="0" name="Header">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" name="Abstract" />
              <xs:element minOccurs="0" name="ApprovedBy" type="xs:string" />
              <xs:element minOccurs="0" name="AreaModel" type="xs:string" />
              <xs:element minOccurs="0" name="AreaModelDate" type="xs:dateTime" />
              <xs:element minOccurs="0" name="Author" type="xs:string" />
              <xs:element minOccurs="0" name="BeingEditedBy" type="xs:string" />
              <xs:element minOccurs="0" name="ClassBased" type="xs:boolean" />
              <xs:element minOccurs="0" name="DBSchema" type="xs:unsignedShort" />
              <xs:element minOccurs="0" name="DefaultSize" type="xs:decimal" />
              <xs:element minOccurs="0" name="Description" type="xs:string" />
              <xs:element minOccurs="0" name="Duration" type="xs:unsignedByte" />
              <xs:element minOccurs="0" name="LocaleID" type="xs:byte" />
              <xs:element minOccurs="0" name="MaxSize" type="xs:decimal" />
              <xs:element minOccurs="0" name="MinSize" type="xs:decimal" />
              <xs:element minOccurs="0" name="ProductCode" type="xs:string" />
              <xs:element minOccurs="0" name="ProductID" type="xs:string" />
              <xs:element minOccurs="0" name="ProductUnits" type="xs:string" />
              <xs:element minOccurs="0" name="RecipeType" type="xs:string" />
              <xs:element minOccurs="0" name="Released" type="xs:unsignedByte" />
              <xs:element minOccurs="0" name="ReleaseAsStep" type="xs:boolean" />
              <xs:element minOccurs="0" name="Resource" />
              <xs:element minOccurs="0" name="VerificationDate" type="xs:dateTime" />
              <xs:element minOccurs="0" name="Version" type="xs:decimal" />
              <xs:element minOccurs="0" name="VersionDate" type="xs:dateTime" />
              <xs:element minOccurs="0" name="Obsoleted" type="xs:boolean" />
              <xs:element minOccurs="0" name="NextWIPNumber" type="xs:unsignedByte" />
              <xs:element minOccurs="0" name="VersionDescription" />
              <xs:element minOccurs="0" name="ParentName" />
              <xs:element minOccurs="0" name="ParentVersionDescription" />
              <xs:element minOccurs="0" name="ParentVersionDate" type="xs:dateTime" />
              <xs:element minOccurs="0" name="ParentVerificationDate" type="xs:dateTime" />
              <xs:element minOccurs="0" name="ParentAreaModelDate" type="xs:dateTime" />
              <xs:element minOccurs="0" name="ParentAreaModelName" />
              <xs:element minOccurs="0" name="SecurityAuthorityIdentifier" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="Parameter">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" name="Name" type="xs:string" />
              <xs:element minOccurs="0" name="ERPAlias" />
              <xs:element minOccurs="0" name="PLCReference" type="xs:unsignedByte" />
              <xs:element minOccurs="0" name="Real" type="xs:unsignedShort" />
              <xs:element minOccurs="0" name="High" type="xs:unsignedShort" />
              <xs:element minOccurs="0" name="Low" type="xs:unsignedByte" />
              <xs:element minOccurs="0" name="EngineeringUnits" type="xs:string" />
              <xs:element minOccurs="0" name="Scale" type="xs:boolean" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="Steps">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" name="InitialStep">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" name="Name" type="xs:string" />
                  </xs:sequence>
                  <xs:attribute name="XPos" type="xs:unsignedShort" use="optional" />
                  <xs:attribute name="YPos" type="xs:unsignedByte" use="optional" />
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" name="TerminalStep">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" name="Name" type="xs:string" />
                  </xs:sequence>
                  <xs:attribute name="XPos" type="xs:unsignedShort" use="optional" />
                  <xs:attribute name="YPos" type="xs:unsignedShort" use="optional" />
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" maxOccurs="unbounded" name="Step">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" name="Name" type="xs:string" />
                    <xs:element minOccurs="0" name="StepRecipeID" type="xs:string" />
                    <xs:element minOccurs="0" name="PackedFlags" type="xs:unsignedByte" />
                    <xs:element minOccurs="0" name="UnitAlias" type="xs:string" />
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="FormulaValue">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="0" name="Name" type="xs:string" />
                          <xs:element minOccurs="0" name="Display" type="xs:boolean" />
                          <xs:element minOccurs="0" name="Value" />
                          <xs:element minOccurs="0" name="String" type="xs:string" />
                          <xs:element minOccurs="0" name="Defer" type="xs:string" />
                          <xs:element minOccurs="0" name="Real" type="xs:decimal" />
                          <xs:element minOccurs="0" name="EngineeringUnits" type="xs:string" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="XPos" type="xs:unsignedShort" use="optional" />
                  <xs:attribute name="YPos" type="xs:unsignedShort" use="optional" />
                  <xs:attribute name="AcquireUnit" type="xs:boolean" use="optional" />
                  <xs:attribute name="SystemStep" type="xs:boolean" use="optional" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="PhaseLinkGroup">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" name="Name" type="xs:string" />
              <xs:element minOccurs="0" maxOccurs="unbounded" name="PhaseLink">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" name="UnitProcedureStepName" type="xs:string" />
                    <xs:element minOccurs="0" name="OperationStepName" type="xs:string" />
                    <xs:element minOccurs="0" name="PhaseStepName" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="Transition">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" name="Name" type="xs:string" />
              <xs:element minOccurs="0" name="ConditionalExpression" type="xs:string" />
            </xs:sequence>
            <xs:attribute name="XPos" type="xs:unsignedShort" use="optional" />
            <xs:attribute name="YPos" type="xs:unsignedShort" use="optional" />
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="ElementLink">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" name="FromStep" type="xs:string" />
              <xs:element minOccurs="0" name="ToTransition" type="xs:string" />
              <xs:element minOccurs="0" name="FromTransition" type="xs:string" />
              <xs:element minOccurs="0" name="ToStep" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="UnitRequirement">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" name="UnitAlias" type="xs:string" />
              <xs:element minOccurs="0" name="ClassInstance" type="xs:string" />
              <xs:element minOccurs="0" name="BindingMethod" type="xs:string" />
              <xs:element minOccurs="0" name="MaterialBindingMethod" type="xs:string" />
              <xs:element minOccurs="0" name="ClassBased" type="xs:boolean" />
              <xs:element minOccurs="0" name="DownstreamResource">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" name="Name" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="Comments" />
        <xs:element minOccurs="0" name="Formulations">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" name="Formulation">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" name="Name" type="xs:string" />
                    <xs:element minOccurs="0" name="Description" type="xs:string" />
                    <xs:element minOccurs="0" name="ParameterList">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="0" maxOccurs="unbounded" name="Parameter">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element minOccurs="0" name="Name" type="xs:string" />
                                <xs:element minOccurs="0" name="Real" type="xs:unsignedShort" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="SchemaVersion" type="xs:unsignedShort" use="optional" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== marcelo-6/ftbatch-recipe-bulk-edit/app/sample_recipe.xml
<?xml version="1.0" encoding="UTF-8"?>
<RecipeElement xmlns="urn:Rockwell/MasterRecipe" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:Rockwell/MasterRecipe C:\Users\marcelo.amorim\Downloads\Temp_deleteMe\xml_tinker\MasterRecipe.xsd" SchemaVersion="3530"><RecipeElementID>CLS_STRAWBERRY_ICEMILK</RecipeElementID><Header><Abstract></Abstract><ApprovedBy>MSS</ApprovedBy><AreaModel>\\NAUSPAZF427R52\BATCHCTL\SAMPLEDEMO1\RECIPES\ICE_CREAM1.CFG</AreaModel><AreaModelDate>2016-12-01T18:24:46</AreaModelDate><Author>Mark Shepard</Author><BeingEditedBy>Not being handled yet</BeingEditedBy><ClassBased>true</ClassBased><DBSchema>3530</DBSchema><DefaultSize>5000.</DefaultSize><Description>Strawberry Ice Milk - Reduced Fat Ice Cream - class based</Description><Duration>45</Duration><LocaleID>-1</LocaleID><MaxSize>7000.</MaxSize><MinSize>3000.</MinSize><ProductCode>SIM-101</ProductCode><ProductID>Strawberry Ice Milk</ProductID><ProductUnits>KG</ProductUnits><RecipeType>Procedure</RecipeType><Released>1</Released><ReleaseAsStep>true</ReleaseAsStep><Resource></Resource><VerificationDate>1950-02-28T00:00:00</VerificationDate><Version>1.0</Version><VersionDate>2025-02-13T12:19:28</VersionDate><Obsoleted>false</Obsoleted><NextWIPNumber>2</NextWIPNumber><VersionDescription></VersionDescription><ParentName></ParentName><ParentVersionDescription></ParentVersionDescription><ParentVersionDate>1950-02-28T00:00:00</ParentVersionDate><ParentVerificationDate>1950-02-28T00:00:00</ParentVerificationDate><ParentAreaModelDate>1950-02-28T00:00:00</ParentAreaModelDate><ParentAreaModelName></ParentAreaModelName><SecurityAuthorityIdentifier>NOT_AVAILABLE</SecurityAuthorityIdentifier></Header><Parameter><Name>FLAVOR_AMOUNT</Name><ERPAlias></ERPAlias><PLCReference>1</PLCReference><Real>50</Real><High>100</High><Low>0</Low><EngineeringUnits>KG</EngineeringUnits><Scale>true</Scale></Parameter><Parameter><Name>MILK_AMT2COOL</Name><ERPAlias></ERPAlias><PLCReference>1</PLCReference><Real>3000</Real><High>5000</High><Low>0</Low><EngineeringUnits>KG</EngineeringUnits><Scale>true</Scale></Parameter><Parameter><Name>MILK_AMT2HEAT</Name><ERPAlias></ERPAlias><PLCReference>1</PLCReference><Real>1000</Real><High>2000</High><Low>0</Low><EngineeringUnits>KG</EngineeringUnits><Scale>true</Scale></Parameter><Parameter><Name>STRAWBERRY_AMT</Name><ERPAlias></ERPAlias><PLCReference>1</PLCReference><Real>250</Real><High>500</High><Low>0</Low><EngineeringUnits>KG</EngineeringUnits><Scale>true</Scale></Parameter><Parameter><Name>SUGAR_AMOUNT</Name><ERPAlias></ERPAlias><PLCReference>1</PLCReference><Real>700</Real><High>1500</High><Low>0</Low><EngineeringUnits>KG</EngineeringUnits><Scale>true</Scale></Parameter><Steps><InitialStep XPos="700" YPos="100"><Name>INITIALSTEP:1</Name></InitialStep><TerminalStep XPos="800" YPos="2500"><Name>TERMINALSTEP:1</Name></TerminalStep><Step XPos="600" YPos="2000" AcquireUnit="true" SystemStep="false"><Name>CLS_STRAWBERRY_IM_UP:1</Name><StepRecipeID>CLS_STRAWBERRY_IM_UP</StepRecipeID><PackedFlags>1</PackedFlags><UnitAlias>FREEZER</UnitAlias><FormulaValue><Name>FLAVOR_AMOUNT</Name><Display>false</Display><Defer>FLAVOR_AMOUNT</Defer><Real>0.0</Real><EngineeringUnits>KG</EngineeringUnits></FormulaValue><FormulaValue><Name>MIXIN_AMOUNT</Name><Display>false</Display><Defer>STRAWBERRY_AMT</Defer><Real>0.0</Real><EngineeringUnits>KG</EngineeringUnits></FormulaValue></Step><Step XPos="600" YPos="600" AcquireUnit="true" SystemStep="false"><Name>CLS_SWEETMILK_UP:1</Name><StepRecipeID>CLS_SWEETMILK_UP</StepRecipeID><PackedFlags>1</PackedFlags><UnitAlias>MIXER</UnitAlias><FormulaValue><Name>MILK_AMT2COOL</Name><Display>false</Display><Defer>MILK_AMT2COOL</Defer><Real>0.0</Real><EngineeringUnits>KG</EngineeringUnits></FormulaValue><FormulaValue><Name>MILK_AMT2HEAT</Name><Display>false</Display><Defer>MILK_AMT2HEAT</Defer><Real>0.0</Real><EngineeringUnits>KG</EngineeringUnits></FormulaValue><FormulaValue><Name>SUGAR_AMOUNT</Name><Display>false</Display><Defer>SUGAR_AMOUNT</Defer><Real>0.0</Real><EngineeringUnits>KG</EngineeringUnits></FormulaValue><FormulaValue><Name>THIS_ONE_IS_NOT_DEFERED</Name><Display>false</Display><Value/><String>YOLO</String></FormulaValue></Step><Step XPos="100" YPos="1300" AcquireUnit="true" SystemStep="false"><Name>CLS_TRANSFER_IN_UP:1</Name><StepRecipeID>CLS_TRANSFER_IN_UP</StepRecipeID><PackedFlags>1</PackedFlags><UnitAlias>FREEZER</UnitAlias></Step><Step XPos="1200" YPos="1300" AcquireUnit="true" SystemStep="false"><Name>CLS_TRANSFER_OUT_UP:1</Name><StepRecipeID>CLS_TRANSFER_OUT_UP</StepRecipeID><PackedFlags>1</PackedFlags><UnitAlias>MIXER</UnitAlias></Step></Steps><PhaseLinkGroup><Name>GROUP1</Name><PhaseLink><UnitProcedureStepName>CLS_TRANSFER_IN_UP:1</UnitProcedureStepName><OperationStepName>CLS_TRANSFER_IN_OP:1</OperationStepName><PhaseStepName>XFR_IN:1</PhaseStepName></PhaseLink><PhaseLink><UnitProcedureStepName>CLS_TRANSFER_OUT_UP:1</UnitProcedureStepName><OperationStepName>CLS_TRANSFER_OUT_OP:1</OperationStepName><PhaseStepName>XFR_OUT:1</PhaseStepName></PhaseLink></PhaseLinkGroup><Transition XPos="800" YPos="398"><Name>T1</Name><ConditionalExpression>[4]</ConditionalExpression></Transition><Transition XPos="800" YPos="900"><Name>T2</Name><ConditionalExpression>CLS_SWEETMILK_UP:1.[21] = [14]</ConditionalExpression></Transition><Transition XPos="800" YPos="1796"><Name>T3</Name><ConditionalExpression>CLS_TRANSFER_OUT_UP:1.[21] = [14] [3] CLS_TRANSFER_IN_UP:1.[21] = [14]</ConditionalExpression></Transition><Transition XPos="800" YPos="2300"><Name>T4</Name><ConditionalExpression>CLS_STRAWBERRY_IM_UP:1.[21] = [14]</ConditionalExpression></Transition><ElementLink><FromTransition>T3</FromTransition><ToStep>CLS_STRAWBERRY_IM_UP:1</ToStep></ElementLink><ElementLink><FromStep>CLS_STRAWBERRY_IM_UP:1</FromStep><ToTransition>T4</ToTransition></ElementLink><ElementLink><FromTransition>T1</FromTransition><ToStep>CLS_SWEETMILK_UP:1</ToStep></ElementLink><ElementLink><FromStep>CLS_SWEETMILK_UP:1</FromStep><ToTransition>T2</ToTransition></ElementLink><ElementLink><FromTransition>T2</FromTransition><ToStep>CLS_TRANSFER_IN_UP:1</ToStep></ElementLink><ElementLink><FromStep>CLS_TRANSFER_IN_UP:1</FromStep><ToTransition>T3</ToTransition></ElementLink><ElementLink><FromTransition>T2</FromTransition><ToStep>CLS_TRANSFER_OUT_UP:1</ToStep></ElementLink><ElementLink><FromStep>CLS_TRANSFER_OUT_UP:1</FromStep><ToTransition>T3</ToTransition></ElementLink><ElementLink><FromStep>INITIALSTEP:1</FromStep><ToTransition>T1</ToTransition></ElementLink><ElementLink><FromTransition>T4</FromTransition><ToStep>TERMINALSTEP:1</ToStep></ElementLink><UnitRequirement><UnitAlias>FREEZER</UnitAlias><ClassInstance>FREEZER_CLS</ClassInstance><BindingMethod>BatchCreation</BindingMethod><MaterialBindingMethod>ByInventory</MaterialBindingMethod><ClassBased>true</ClassBased></UnitRequirement><UnitRequirement><UnitAlias>MIXER</UnitAlias><ClassInstance>MIXER_CLS</ClassInstance><BindingMethod>BatchCreation</BindingMethod><MaterialBindingMethod>ByInventory</MaterialBindingMethod><ClassBased>true</ClassBased><DownstreamResource><Name>FREEZER</Name></DownstreamResource></UnitRequirement><Comments/><Formulations><Formulation><Name>MA_TEST_FORMULA_01</Name><Description>666 is the beast</Description><ParameterList><Parameter><Name>FLAVOR_AMOUNT</Name><Real>66</Real></Parameter><Parameter><Name>MILK_AMT2COOL</Name><Real>666</Real></Parameter><Parameter><Name>MILK_AMT2HEAT</Name><Real>666</Real></Parameter><Parameter><Name>STRAWBERRY_AMT</Name><Real>66</Real></Parameter><Parameter><Name>SUGAR_AMOUNT</Name><Real>666</Real></Parameter></ParameterList></Formulation></Formulations></RecipeElement>
